[[ranks]]
  tier = 0
  numAffixes = 0
  defaultColor = 0xffffff
  chance = 1.0
  growthFactor = 0
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 1
  numAffixes = 1
  defaultColor = 0xffff00
  chance = 0.07
  growthFactor = 1
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 2
  numAffixes = 2
  defaultColor = 0xff9900
  chance = 0.4
  growthFactor = 3
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 3
  numAffixes = 3
  defaultColor = 0x66ffff
  chance = 0.3
  growthFactor = 5
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 4
  numAffixes = 4
  defaultColor = 0xcc33ff
  chance = 0.2
  growthFactor = 7
  effects = []
  presetAffixes = []