
[general]
	#Enable concrete slabs
	enableSlabs = true
	#Enable concrete stairs
	enableStairs = true
	#Enable concrete walls
	enableWalls = true
	#Enable concrete buttons
	enableButtons = true
	#Enable concrete pressure plates
	enablePressurePlates = true
	#Enable concrete fences
	enableFences = true
	#Enable concrete ladders
	enableLadders = true
	#Enable concrete cake
	enableCake = true
	#Enable concrete signs
	enableSigns = true
	#Enable concrete levers
	enableLevers = true
	#Enable concrte vertical slabs
	enableVerticalSlabs = true
	#Enable concrete powder layers
	enablePowderLayers = true

