
#General settings
[general]
	#Cost
	#Range: > -2147483648
	cost = 8
	#The maximum number of times this glyph may appear in a single spell
	#Range: > 1
	per_spell_limit = 2
	#Is Starter Glyph?
	starter = false
	#Is Enabled?
	enabled = true

